FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    curl \
    gnupg2 \
    apt-transport-https \
    ca-certificates \
    gcc \
    g++ \
    make \
    unixodbc \
    unixodbc-dev \
    libpq-dev

# Microsoft key + repo بالطريقة الصحيحة
RUN curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/debian/12/prod bookworm main" > /etc/apt/sources.list.d/mssql-release.list


# تحديث الـ repo وتثبيت الدرايفر
RUN apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql17

# تنظيف الكاش
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# نسخ الكود وتشغيل التطبيق
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python3", "app.py"]